# Generated by Django 5.0.4 on 2024-04-20 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateTimeField()),
                ('description', models.TextField()),
                ('estimate', models.DurationField()),
                ('status', models.IntegerField(choices=[(0, 'NOT_STARTED'), (1, 'STARTED'), (2, 'COMPLETED'), (3, 'DELETED')])),
                ('weight', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Frog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateTimeField()),
                ('description', models.TextField()),
                ('estimate', models.DurationField()),
                ('status', models.IntegerField(choices=[(0, 'NOT_STARTED'), (1, 'STARTED'), (2, 'COMPLETED'), (3, 'DELETED')])),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frogapp.task')),
            ],
        ),
    ]
